export const appReviewsById: Record<string, { quote: string; author: string; rating?: number }[]> = {
  habiteazy: [
    { quote: "This app makes building good habits fun and rewarding. It gamifies daily chores, turning routine tasks into small achievements that keep me motivated.", author: "Kunal" },
    { quote: "I've used a lot of habit trackers and games, and I really like this one. It's easy to add tasks and habits and configure them to meet my needs. It doesn't have a ton of ads, and right now the premium is only about $2/month so it's affordable. I work a flexible schedule of 50hr/week with my schedule changing with less than a day's notice, regularly. This app makes it much easier to organize my life despite the chaos and lack of time.", author: "Amanda" },
    { quote: "I love this app. Much easier to use than other apps like it. The UI is simple, making it easier to do what you want. The widget is perfect. I can't find anything wrong with it. Looking forward to future updates. Try this app. You won't be sorry.", author: "Koni" },
    { quote: "Guys this is super cute and fantastic!", author: "Myat" },
  ],
  banknotes: [
    { quote: "I make money in various currencies and this app is very very helpful in identifying the money that I have made in the different currencies. Good community.", author: "Kirti" },
    { quote: "Best banknote identifier with good accuracy. A must for casual users and collectors.", author: "Chitvan" },
    { quote: "Nice application for identification.", author: "Jaya" },
  ],
  coinzy: [
    { quote: "As an avid collector of US coins and currency for over 20 years, I can say I love the concept of the app and the fact that there's an included community within the app that allows us to interact amongst each other.", author: "Jaylin" },
    { quote: "Good coin scanner.", author: "Naing" },
    { quote: "It's very good and helps a lot.", author: "Colete" },
    { quote: "This is a great app for coin collectors. It's helpful in cataloging the collection virtually. Also, it provides visibility on the coins that have not been collected by me yet.", author: "Ankit" },
    { quote: "Accurate and awesome tool utility.", author: "Pierre" },
  ],
  insecto: [
    { quote: "The app has a great UI with quick turnaround time to satisfy my curiosity.", author: "Aanish" },
    { quote: "Decent repertoire of insects available for identifying them.", author: "Pintu" },
    { quote: "Amazing app with such a vast library of readily available insects.", author: "Pallav" },
    { quote: "Best app to identify insects!!!", author: "Jay" },
  ],
  rockzy: [
    { quote: "I could easily identify some rocks in the wild with this app. Waiting for an offline version to happen soon!", author: "Pintu Bodat" },
    { quote: "Good app. I like my hobby to collect rocks and minerals and this app certainly helps identify them!", author: "Umesh Barot" },
    { quote: "Great app with brilliant UI to identify rocks and minerals just by a click of the camera!", author: "Aanish Aggarwal" },
    { quote: "Great for geology lovers! It's so simple to identify rocks by photo and then track your rock collection as it grows. Best rock identifier on the play store by far. Highly recommend!", author: "Chitvan Singhal" },
    { quote: "If you enjoy collecting minerals, this rock identifier is a must have. You can identify rocks by photo within seconds and track your collection easily.", author: "Ijaaz Ahamed" },
    { quote: "Really nice app, smooth ui and great scanning accuracy of gems, useful to identify rocks or gems using camera.", author: "Aishik Kirtaniya" },
  ],
  plantzy: [
    { quote: "Helps me remember watering and names the plants I pick up at the nursery.", author: "Aanya" },
  ],
};

export const appFaqsById: Record<string, { q: string; a: string }[]> = {
  insecto: [
    { q: 'How do I use the insect identification feature?', a: 'To identify an insect, tap the Identify button on the home screen. You can either capture a new photo or upload one from your gallery. Crop or adjust the image if needed, then submit it to get the result. You\'ll see a primary result, along with a horizontally scrollable section showing all matches and a View All button to see the full list. You can then save the result to your collection or explore more details.' },
    { q: 'How do I use the "Something bit me" feature?', a: 'If you\'ve been bitten, go to What to do → Something bit me. Upload a picture of the bite mark and a photo of the insect. The app cannot identify the insect from the bite mark alone, so the insect photo is needed to provide bite-related information such as venom risk, symptoms, and suggested treatments.' },
    { q: 'Why am I not getting a proper response from the AI?', a: 'AI answers depend on the quality of your question and the available insect data. If the response seems unclear: Try rephrasing your question, provide context, and ensure you\'re connected to the internet.' },
    { q: 'How can I chat better with Ask AI?', a: 'Be specific and clear. Free users get 5 questions per day, while Premium users have unlimited conversations.' },
    { q: 'What is the "Which insect are you?" feature?', a: 'This is a fun feature that lets you discover your insect personality.' },
    { q: 'What do I get as a Premium user?', a: 'Premium unlocks: Unlimited identifications, unlimited collections, full insect details, unlimited Ask AI questions, unlimited feed posts, and an ad-free experience.' },
    { q: 'Can I use the app offline?', a: 'No. The app currently requires an internet connection.' },
    { q: 'Why am I not able to identify more insects?', a: 'Free users can identify 2 insects per day.' },
    { q: 'Why can\'t I ask more questions in Ask AI?', a: 'Free users can ask 5 questions per day.' },
    { q: 'How accurate is the insect identification?', a: 'The AI is trained on thousands of species and shows a primary result plus possible matches.' },
    { q: 'How do I create and manage insect collections?', a: 'Tap Add to Collection after identification. Premium users get unlimited collections.' },
    { q: 'How do I share an insect I identified?', a: 'Use the Share icon from the result screen.' },
    { q: 'How do I delete my account?', a: 'Go to Settings → Account Actions → Delete Account.' },
    { q: 'How do I cancel my subscription?', a: 'Cancel through Google Play subscriptions page.' },
    { q: 'Why can\'t I create more posts?', a: 'Free users can create 1 post per day.' },
    { q: 'Why can\'t I refresh Insect of the Day again?', a: 'Free users see it once per day, Premium can refresh multiple times.' },
    { q: 'What should I do if the app cannot identify an insect?', a: 'Try uploading a clearer photo with better lighting and angle.' },
  ],
  habiteazy: [
    { q: 'How do I create a new habit?', a: 'Tap the "+" button on the home screen, enter your habit name, choose a category, set a schedule and reminder time, then save. Your habit will appear on the dashboard immediately.' },
    { q: 'How does streak tracking work?', a: 'Complete your habit each day to build a streak. The app tracks consecutive days and rewards you with badges and visual progress indicators. Missing a day resets your streak, but your overall history is preserved.' },
    { q: 'Can I track tasks as well as habits?', a: 'Yes! Habiteazy supports both habits (recurring) and tasks (one-time to-dos). You can manage them from the same dashboard.' },
    { q: 'What is the difference between Free and Premium?', a: 'Free users can track up to 3 habits with basic stats. Premium unlocks unlimited habits, advanced analytics, widgets, watch support, and an ad-free experience.' },
    { q: 'How do I use the widget?', a: 'After adding habits, long-press your home screen, select Widgets, find Habiteazy, and add it. The widget lets you mark habits complete without opening the app.' },
    { q: 'Can I see detailed statistics and reports?', a: 'Yes! Go to the Stats tab to view daily, weekly, and monthly completion rates, streak history, heat maps, and trend charts.' },
    { q: 'How do reminders work?', a: 'Set custom reminder times for each habit. You can choose specific days, multiple times per day, and the app will send push notifications at those times.' },
    { q: 'Does the app support smartwatch?', a: 'Yes, Premium users can view and complete habits from their Apple Watch or Wear OS device.' },
    { q: 'How do I reorder or organize my habits?', a: 'Long-press a habit on the dashboard and drag to reorder. You can also group habits by category for better organization.' },
    { q: 'Can I set habits for specific days only?', a: 'Yes! When creating or editing a habit, choose which days of the week it should be active. It will only appear on those days.' },
    { q: 'How do I delete or archive a habit?', a: 'Swipe left on a habit or go to its edit screen and tap Delete. You can also archive habits to keep their history without cluttering your dashboard.' },
    { q: 'Is my data synced across devices?', a: 'Yes, once you sign in with your account, all habits, streaks, and stats sync automatically across your devices.' },
    { q: 'How do I reset my streak?', a: 'Streaks reset automatically if you miss a day. There is no manual reset option to ensure accurate tracking.' },
    { q: 'Can I export my habit data?', a: 'Premium users can export their habit history and statistics as CSV or PDF from the Settings screen.' },
    { q: 'How do I provide feedback or report a bug?', a: 'Go to Settings → Help & Feedback. You can send us a message directly from within the app and our team will respond promptly.' },
    { q: 'How do I cancel my subscription?', a: 'Cancel through the App Store (iOS) or Google Play Store (Android) subscription management page.' },
    { q: 'How do I delete my account?', a: 'Go to Settings → Account Actions → Delete Account. This will permanently remove all your data.' },
    { q: 'What happens to my data if I uninstall the app?', a: 'If you have an account, your data remains saved in the cloud. Reinstall and sign in to restore everything. Without an account, local data will be lost.' },
  ],
  coinzy: [
    { q: 'How do I identify a coin?', a: 'Tap the Scan button on the home screen, point your camera at the coin or upload a photo from your gallery. The AI will identify it and show detailed information including country, year, denomination, and estimated value.' },
    { q: 'How accurate is the coin identification?', a: 'Coinzy uses advanced AI trained on millions of coin images, achieving high accuracy for most commonly circulated coins worldwide. Results include a confidence score and possible alternative matches.' },
    { q: 'What is the Marketplace?', a: 'The Marketplace lets you buy and sell coins with other collectors. You can list coins for sale, browse listings, and connect with buyers and sellers in a trusted community.' },
    { q: 'How does the Global Catalogue work?', a: 'The Global Catalogue is a comprehensive database of coins from around the world. Browse by country, era, or denomination to explore coins and learn about their history and value.' },
    { q: 'How do I create and manage collections?', a: 'After identifying a coin, tap "Add to Collection." You can create multiple named collections, organize coins by theme, and track your collection\'s completeness and estimated value.' },
    { q: 'What is the Feed feature?', a: 'The Feed is a social feature where you can share your coin finds, see what other collectors are discovering, and interact with the community through likes and comments.' },
    { q: 'What is Coin of the Day?', a: 'Every day, a featured coin is highlighted with detailed history, fun facts, and rarity information. Premium users can refresh to see additional featured coins.' },
    { q: 'What is the difference between Free and Premium?', a: 'Free users can scan a limited number of coins per day with basic details. Premium unlocks unlimited scans, full coin details, unlimited collections, unlimited feed posts, and an ad-free experience.' },
    { q: 'Can I use the app offline?', a: 'Your saved collections and basic browsing work offline. Coin scanning, marketplace, and feed features require an internet connection.' },
    { q: 'How do I share a coin I identified?', a: 'Use the Share icon from the coin result screen to share via social media, messaging apps, or copy a link.' },
    { q: 'How do I sell a coin on the Marketplace?', a: 'Go to Marketplace → Sell, upload photos of your coin, add a description and price, and publish your listing. Interested buyers can contact you through the app.' },
    { q: 'Is my payment information secure?', a: 'Yes, all payment processing is handled through secure, encrypted channels via the App Store or Google Play. We never store your payment details.' },
    { q: 'How do I delete my account?', a: 'Go to Settings → Account Actions → Delete Account. This will permanently remove all your data and collections.' },
    { q: 'How do I cancel my subscription?', a: 'Cancel through the App Store (iOS) or Google Play Store (Android) subscription management page.' },
    { q: 'Why can\'t I scan more coins?', a: 'Free users have a daily scan limit. Upgrade to Premium for unlimited coin identifications.' },
    { q: 'Why can\'t I create more posts?', a: 'Free users can create a limited number of posts per day. Premium users have unlimited posting.' },
    { q: 'How do I report a bug or incorrect identification?', a: 'Go to Settings → Help & Feedback. Describe the issue and our team will review it. Your feedback helps improve our AI.' },
    { q: 'What should I do if the app cannot identify a coin?', a: 'Try uploading a clearer photo with better lighting, ensuring both sides of the coin are visible. You can also try the manual search in the Global Catalogue.' },
  ],
  banknotes: [
    { q: 'How do I identify a banknote?', a: 'Tap the Scan button on the home screen, point your camera at the banknote or upload a photo. The AI will identify the country, denomination, year, and provide detailed information.' },
    { q: 'How accurate is the banknote identification?', a: 'Our AI is trained on banknotes from over 150 countries and achieves high accuracy. Results include confidence scores and alternative matches for similar-looking notes.' },
    { q: 'How do I create and manage collections?', a: 'After identifying a banknote, tap "Add to Collection." Create multiple collections, organize by country or theme, and track your collection progress.' },
    { q: 'What is the Marketplace?', a: 'The Marketplace connects banknote collectors for buying and selling. List your notes, browse others\' listings, and communicate securely within the app.' },
    { q: 'How does the Global Catalogue work?', a: 'Browse a comprehensive database of banknotes from around the world. Filter by country, era, or denomination to explore and learn about banknotes.' },
    { q: 'What is the Feed feature?', a: 'Share your banknote finds with the community, see other collectors\' discoveries, and interact through likes and comments.' },
    { q: 'What is Banknote of the Day?', a: 'A daily featured banknote with detailed history, design information, and fun facts. Premium users can refresh for more featured notes.' },
    { q: 'What is the difference between Free and Premium?', a: 'Free users can scan a limited number of banknotes per day with basic info. Premium unlocks unlimited scans, full details, unlimited collections, unlimited feed posts, and an ad-free experience.' },
    { q: 'Can I check if a banknote is counterfeit?', a: 'While the AI can identify banknotes and highlight security features, we recommend professional verification for authenticity confirmation.' },
    { q: 'Does it show exchange rates?', a: 'Yes, the app displays current exchange rates for identified currencies, updated regularly to reflect market conditions.' },
    { q: 'Can I use the app offline?', a: 'Your saved collections and basic browsing work offline. Scanning, marketplace, and feed features require an internet connection.' },
    { q: 'How do I share a banknote I identified?', a: 'Use the Share icon from the result screen to share via social media, messaging apps, or copy a link.' },
    { q: 'How do I sell a banknote on the Marketplace?', a: 'Go to Marketplace → Sell, upload photos, add description and price, and publish. Buyers can contact you through the app.' },
    { q: 'Is my payment information secure?', a: 'Yes, all payment processing is handled through secure, encrypted channels via the App Store or Google Play. We never store your payment details.' },
    { q: 'How do I delete my account?', a: 'Go to Settings → Account Actions → Delete Account. This permanently removes all your data.' },
    { q: 'How do I cancel my subscription?', a: 'Cancel through the App Store (iOS) or Google Play Store (Android) subscription management page.' },
    { q: 'How do I report a bug or incorrect identification?', a: 'Go to Settings → Help & Feedback. Describe the issue and our team will review it promptly.' },
    { q: 'What should I do if the app cannot identify a banknote?', a: 'Try uploading a clearer photo with better lighting. Ensure the full banknote is visible. You can also search manually in the Global Catalogue.' },
  ],
  rockzy: [
    { q: 'What is Rockzy?', a: 'Rockzy is a comprehensive rocks and minerals app that helps you identify, collect, and organize rocks and minerals using AI.' },
    { q: 'Why can\'t I identify more rocks?', a: 'Free users have a daily limit of 2 identifications. This resets every 24 hours. Upgrade to Premium for unlimited use.' },
    { q: 'How does identification work?', a: 'Take a clear photo → AI analyzes → returns name, type, and details.' },
    { q: 'Do I need an account?', a: 'You can use as guest, but account is required for saving collections.' },
    { q: 'What happens if I delete the app?', a: 'Guest data is lost. Account data is restored on login.' },
    { q: 'Free vs Premium?', a: 'Free: Limited identifications and collections. Premium: Unlimited identifications, unlimited collections, and full AI chat access.' },
    { q: 'Can I cancel the subscription?', a: 'Yes, via Play Store / App Store settings.' },
    { q: 'How to organise a collection?', a: 'Use Owned, Identified, Wishlist categories.' },
    { q: 'What is "Which Rock Are You"?', a: 'A personality quiz that matches you with a rock.' },
    { q: 'What are Zodiac Stones?', a: 'Crystals linked to zodiac signs and energies.' },
    { q: 'How does AI Chat work?', a: 'Ask questions about rocks and minerals. Free has limits, Premium is unlimited.' },
    { q: 'What is Global Catalogue?', a: 'A database of rocks and minerals worldwide.' },
    { q: 'What is Rock of the Day?', a: 'A daily featured mineral with details and insights.' },
    { q: 'How accurate is identification?', a: 'Depends on image quality. AI gives multiple possible matches.' },
    { q: 'Is my data safe?', a: 'Yes, securely stored with encryption.' },
    { q: 'How to report content?', a: 'Use the report option in the app.' },
  ],
  plantzy: [
    {
      q: 'What is Plantzy AI?',
      a: 'Plantzy AI is an all-in-one app that lets you identify plants instantly using your camera, manage your personal collection, and browse our global plants catalogue. It provides personalized care guidance and a dedicated AI chat to answer your specific gardening questions, helping you grow smarter every day.',
    },
    {
      q: "Why can't I identify more plants?",
      a: 'Free users are limited to 2 successful plant identifications per day. Once you have reached this limit, you will need to wait for it to reset every 24 hours. To remove these restrictions and enjoy unlimited identifications immediately, you can upgrade your account to Premium.',
    },
    {
      q: 'How does plant identification work?',
      a: 'Take clear photos of your plant using the Identify feature. Our AI analyzes the images and provides details such as name, species, traits, and care recommendations. Free users can identify up to the daily limit, while Premium users have unlimited access.',
    },
    {
      q: 'Do I need to create an account?',
      a: 'Plantzy AI allows you to browse as a guest; however, guest data is stored only on your local device. This means your collection may be lost if the app is deleted, the device cache is cleared, or storage is deleted. Creating an account ensures your data is securely saved and synced across all your devices.',
    },
    {
      q: 'What happens to my data if I delete the app?',
      a: 'If you have an account, your data is stored securely on our servers and restored when you sign in again. Guest data stored on the device will be lost. You can also request account deletion anytime from Settings.',
    },
    {
      q: "What's the difference between free and premium?",
      a: 'Free users have limits on identifications, plant details access, and collections, and can view 1 Plant of the Day. Premium removes these limits and provides full access to all features, including unlimited AI chat.',
    },
    {
      q: 'Can I cancel my subscription?',
      a: 'Yes, you can cancel your subscription at any time through the App Store or Google Play Store settings, depending on your device. Once canceled, your Premium access will continue until the end of your current billing period, after which your account will return to the free tier. By staying subscribed, you ensure uninterrupted access to all Premium benefits. If you choose to cancel, you can always resubscribe later at any time.',
    },
    {
      q: 'How do I organise my plant collection?',
      a: 'You can organize plants using Identified, Wishlist, Indoor and Outdoor collections. Premium users can create unlimited custom collections and categorize plants in multiple ways.',
    },
    {
      q: 'How do I add plants to my collection?',
      a: 'You can identify a plant with the camera, mark plants as Wishlist in the Global Catalogue, or manually create a new entry with details and photos.',
    },
    {
      q: 'What calculators and tools are available?',
      a: 'Plantzy AI includes specialized tools like the Sunlight (Light) Meter, Water Calculator, Pot Size Calculator, and Plant Disease Detector. These tools provide practical guidance based on your plant and environment to help with your day-to-day care decisions.',
    },
    {
      q: 'How do sunlight and other meters work?',
      a: 'The Sunlight (Light) Meter helps you check whether your plant is getting enough light. The Water Calculator helps estimate watering needs, and the Pot Size Calculator helps choose suitable pot dimensions. Use these tools with your plant details for better recommendations.',
    },
    {
      q: 'What are special features in the app?',
      a: 'Special features include Plant of the Day, AI Chat for plant questions, care reminders, diagnose disease and smart calculators. Some advanced features are limited for free users and fully unlocked with Premium.',
    },
    {
      q: 'How does AI chat work?',
      a: 'Ask AI is your smart plant assistant. You can ask questions about plant care, get help with identification, and chat for tips and learning. Free users have limited AI messages per day; Premium users have unlimited access.',
    },
    {
      q: 'What is the Global Catalogue?',
      a: 'The Global Catalogue is a searchable database of plants worldwide where you can browse details and track which plants you own, have identified, or wishlisted.',
    },
    {
      q: 'What is Plant of the Day?',
      a: 'Plant of the Day is a featured plant highlighted daily in the app, showcasing interesting details and care insights to help you discover new plants. Free users can view one Plant of the Day, while Premium users can access multiple featured items and full details without limits.',
    },
    {
      q: 'How accurate is plant identification?',
      a: 'The AI provides multiple possible matches with confidence levels. Best results require clear lighting, good focus, and clear photos of the plant.',
    },
    {
      q: 'Is my personal information secure?',
      a: 'Yes. Your data is encrypted, securely stored, and protected using industry-standard security practices. Details are available in the Privacy Policy and Terms.',
    },
    {
      q: 'How do I report inappropriate content?',
      a: 'Use the report option on the relevant content. Our team reviews reports and takes appropriate action.',
    },
    {
      q: 'Can I export my collection data?',
      a: 'Collection export is not available yet, but your data is securely stored and synced across all signed-in devices.',
    },
  ],
};
